{{- range .Values.instances }}
{{- if (default $.Values.defaults.nvdsanalytics.enabled (default (dict "enabled" $.Values.defaults.nvdsanalytics.enabled) .nvdsanalytics).enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-analytics-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
  annotations:
    {{- toYaml (default $.Values.defaults.annotations .annotations) | nindent 4 }}
data:
  config_nvdsanalytics.txt: |
    {{- (default $.Values.defaults.nvdsanalytics.config (default (dict "config" $.Values.defaults.nvdsanalytics.config) .nvdsanalytics).config) | nindent 4 }}
{{- end -}}
{{- end }}