apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "%s-env-config" (include "nvr.fullname" .) }}"
  labels:
    app: nvr
data:
  MQTT_CLIENT_ID: {{ include "nvr.fullname" . }}
  MQTT_SERVICE_HOST: "mqtt.kube-system"
  DEBUG_LEVEL: "DEBUG"
  ENABLE_MQTT_STATE: "true"
  ALLOW_NON_INFERENCE_FRAMES: "true"
  ALLOW_NON_MOTION_FRAMES: "true"
  MOTION_ACTIVE_INTERVAL: "0"
  MOTION_INACTIVE_INTERVAL: "900"
  PERIPHERAL_TYPE: "camera"
  PERIPHERAL_NAME: {{ include "nvr.fullname" . }}
  # Variable substitution in GST_PIPELINE_TEMPLATE replaces "camera_id"
  PERIPHERAL_ID: {{ include "nvr.fullname" . }}
  # Variable substitution in GST_PIPELINE_TEMPLATE replaces "uri"
  PERIPHERAL_STREAM_URI: "rtsp://rtsp-video-file-streams:8554/vid5"
  GST_PIPELINE_TEMPLATE: "videotestsrc pattern=ball ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! ! tee name=t t. ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvvideoconvert ! queue ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink t. ! nvvideoconvert ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! nvvideoconvert ! motioncells threshold=0.0001 gridx=32 gridy=18 ! fakesink"
  # Deprecated in favor of ORG TREE
  LOCATION_COUNTRY: "us"
  LOCATION_REGION: "texas"
  LOCATION_BRANCH: "houston"
  LOCATION_FACILITY: "office"
  LOCATION_SITE: "interior"
  LOCATION_ZONE: "test"
  LOCATION_GROUP: "poc"
