apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvr.configmapName" . }}
  labels:
    app: nvr
data:
  DEBUG_LEVEL: "{{ .Values.nvr.debugLevel }}"
  MQTT_CLIENT_ID: "{{ include "nvr.fullname" . }}"
  MQTT_SERVICE_HOST: "{{ .Values.nvr.mqtt.broker }}"
  MQTT_SERVICE_PORT: "{{ .Values.nvr.mqtt.port }}"
  MQTT_QOS: "{{ .Values.nvr.mqtt.qos }}"
  MQTT_KEEP_ALIVE_INTERVAL: "{{ .Values.nvr.mqtt.keepAliveInterval }}"
  MQTT_CONNECT_RETRY_INTERVAL: "{{ .Values.nvr.mqtt.connectRetryInterval }}"
  MQTT_OUT_PREFIX: "{{ .Values.nvr.mqtt.topicPrefix }}"
  MQTT_QUEUE_LIMIT: "{{ .Values.nvr.mqtt.queueLimit }}"
  ENABLE_MQTT_STATE: "{{ .Values.nvr.mqtt.metrics }}"
  METRICS_STATE_TOPIC: "{{ .Values.nvr.mqtt.metricsTopic }}"
  ALLOW_NON_INFERENCE_FRAMES: "{{ .Values.nvr.mqtt.nonInferenceEvents }}"
  ALLOW_NON_MOTION_FRAMES: "{{ .Values.nvr.mqtt.nonMotionEvents }}"
  MOTION_ACTIVE_INTERVAL: "{{ .Values.nvr.motion.activeInterval }}"
  MOTION_INACTIVE_INTERVAL: "{{ .Values.nvr.motion.inactiveInterval }}"
  PERIPHERAL_TYPE: "{{ .Values.nvr.camera.type }}"
  PERIPHERAL_NAME: "{{ include "nvr.fullname" . }}"
  # Variable substitution in GST_PIPELINE_TEMPLATE replaces "camera_id"
  PERIPHERAL_ID: "{{ include "nvr.fullname" . }}"
  # Variable substitution in GST_PIPELINE_TEMPLATE replaces "uri"
  PERIPHERAL_STREAM_URI: "{{ .Values.nvr.camera.uri }}"
  GST_PIPELINE_TEMPLATE: "{{ .Values.nvr.camera.pipeline }}"
  # Deprecated in favor of ORG TREE
  LOCATION_COUNTRY: "{{ .Values.nvr.location.country }}"
  LOCATION_REGION: "{{ .Values.nvr.location.region }}"
  LOCATION_BRANCH: "{{ .Values.nvr.location.branch }}"
  LOCATION_FACILITY: "{{ .Values.nvr.location.facility }}"
  LOCATION_SITE: "{{ .Values.nvr.location.site }}"
  LOCATION_ZONE: "{{ .Values.nvr.location.zone }}"
  LOCATION_GROUP: "{{ .Values.nvr.location.group }}"
