{{- range .Values.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- toYaml (default $.Values.defaults.annotations .annotations) | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        teknoir.org/app: {{ .name }}
        app: {{ .name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
        checksum/config-env: {{ include (print $.Template.BasePath "/configmap_env.yaml") $ | sha256sum }}
        checksum/config-nvdsanalytics: {{ tpl (default $.Values.defaults.nvdsanalytics.config (default (dict "config" $.Values.defaults.nvdsanalytics.config) .nvdsanalytics).config) . | toJson | sha256sum }}
        checksum/config-nvdewarper: {{ tpl (default $.Values.defaults.nvdewarper.config (default (dict "config" $.Values.defaults.nvdewarper.config) .nvdewarper).config) . | toJson | sha256sum }}
        {{- toYaml (default $.Values.defaults.annotations .annotations) | nindent 8 }}
    spec:
      runtimeClassName: nvidia
{{- if not (empty (default $.Values.defaults.trackers .trackers)) }}
      initContainers:
{{- range (default $.Values.defaults.trackers .trackers) }}
        - name: init-container-{{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          volumeMounts:
            - name: tracker-volume
              mountPath: /trackers
{{- end }}
{{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ default $.Values.defaults.image.repository (default (dict "repository" $.Values.defaults.image.repository) .image).repository }}:{{ default $.Values.defaults.image.tag (default (dict "tag" $.Values.defaults.image.tag) .image).tag }}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: {{ default $.Values.defaults.livenessProbe.initialDelaySeconds (default (dict "initialDelaySeconds" $.Values.defaults.livenessProbe.initialDelaySeconds) .livenessProbe).initialDelaySeconds }}
            periodSeconds: {{ default $.Values.defaults.livenessProbe.periodSeconds (default (dict "periodSeconds" $.Values.defaults.livenessProbe.periodSeconds) .livenessProbe).periodSeconds }}
            failureThreshold: {{ default $.Values.defaults.livenessProbe.failureThreshold (default (dict "failureThreshold" $.Values.defaults.livenessProbe.failureThreshold) .livenessProbe).failureThreshold }}
          envFrom:
            - configMapRef:
                name: {{ .name }}-env-config
          resources:
            {{- toYaml (default $.Values.defaults.resources .resources) | nindent 12 }}
          volumeMounts:
            - name: model-volume
              mountPath: /models
            - name: tracker-volume
              mountPath: /trackers
            - name: video-storage
              mountPath: /app/videos
            {{- if (default $.Values.defaults.nvdsanalytics.enabled (default (dict "enabled" $.Values.defaults.nvdsanalytics.enabled) .nvdsanalytics).enabled) }}
            - name: nvdsanalytics-config
              mountPath: {{ default $.Values.defaults.nvdsanalytics.mountPath (default (dict "mountPath" $.Values.defaults.nvdsanalytics.mountPath) .nvdsanalytics).mountPath }}
            {{- end }}
            {{- if (default $.Values.defaults.nvdewarper.enabled (default (dict "enabled" $.Values.defaults.nvdewarper.enabled) .nvdewarper).enabled) }}
            - name: nvdewarper-config
              mountPath: {{ default $.Values.defaults.nvdewarper.mountPath (default (dict "mountPath" $.Values.defaults.nvdewarper.mountPath) .nvdewarper).mountPath }}
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: model-volume
          hostPath:
            path: {{ default $.Values.defaults.modelRepositoryPath .modelRepositoryPath }}
            type: DirectoryOrCreate
        - name: tracker-volume
          hostPath:
            path: {{ default $.Values.defaults.trackerRepositoryPath .trackerRepositoryPath }}
            type: DirectoryOrCreate
        - name: video-storage
          hostPath:
            path: {{ default $.Values.defaults.videoStoragePath .videoStoragePath }}
            type: DirectoryOrCreate
        {{- if (default $.Values.defaults.nvdsanalytics.enabled (default (dict "enabled" $.Values.defaults.nvdsanalytics.enabled) .nvdsanalytics).enabled) }}
        - name: nvdsanalytics-config
          configMap:
            name: {{ .name }}-analytics-config
        {{- end }}
        {{- if (default $.Values.defaults.nvdewarper.enabled (default (dict "enabled" $.Values.defaults.nvdewarper.enabled) .nvdewarper).enabled) }}
        - name: nvdewarper-config
          configMap:
            name: {{ .name }}-dewarper-config
        {{- end }}
        # Nvidia has the argus socket mounted under /tmp/argus_socket
        - name: tmp
          hostPath:
            path: /tmp
            type: DirectoryOrCreate
  {{- end }}