# Example for minimal configuration
instances:
  - name: camera-default-name

# Values possible for Teknoir AI NVRs
defaults:
  name: camera-default-name
  camera:
    type: camera
    uri: rtsp://host:port/path
    # GST pipeline variable substitution:
    # - uri: nvr.camera.uri
    # - camera_id: release full name | fullnameOverride
    pipeline: videotestsrc ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! tee name=t t. ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvvideoconvert ! queue ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink t. ! nvvideoconvert ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! nvvideoconvert ! motioncells threshold=0.0001 gridx=32 gridy=18 ! fakesink
  # The path to the models directory
  modelRepositoryPath: /opt/teknoir/models
  # The path to the video storage
  videoStoragePath: /tmp/teknoir/videos
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/nvr
    # Overrides the image tag whose default is "ds7-gst1.24.7".
    # ds7-gst1.24.7: Nvidia Ada Lovelace GPU on AMD64
    # ds7-gst1.24.7-l4t: Nvidia Orin(tegra) on ARM64
    tag: ds7-gst1.24.7
  # Set the log level for the nvr
  # - DEBUG
  # - INFO
  # - WARNING
  # - ERROR
  debugLevel: INFO
  mqtt:
    # Local MQTT broker
    broker: mqtt.kube-system
    port: 1883
    qos: 2
    keepAliveInterval: 10
    connectRetryInterval: 10
    # Topic prefix for generated topic <topicPrefix>/<camera_id: release full name | fullnameOverride>
    topicPrefix: camera/frames
    # Number of frames to queue before dropping
    queueLimit: 15
    # Send metrics collected through MQTT
    metrics: true
    metricsTopic: toe/state
    # Send events without inference calculated
    nonInferenceEvents: true
    # Send events without motion detected
    nonMotionEvents: true
  motion:
    # Number of frames to skip inference when no motion detected
    inactiveInterval: 900
    # Number of frames to skip inference when motion is detected
    activeInterval: 0
  healthz:
    fpsThreshold: 0.01
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nvdsanalytics:
    enabled: false
    # Mount path for the nvdsanalytics config file: <mountPath>/config_nvdsanalytics.txt
    mountPath: /app/config
    config: |
      [property]
      enable=0
      config-width=1920
      config-height=1080
      osd-mode=0
      display-font-size=25
  # Deprecated in favor of ORG TREE
  location:
    country: "us"
    region: "texas"
    branch: "houston"
    facility: "office"
    site: "interior"
    zone: "test"
    group: "poc"

