# Example for minimal configuration
instances:
  - name: camera-default-name

# Values possible for Teknoir AI NVRs
defaults:
  name: camera-default-name
  annotations: { }
  camera:
    type: camera
    uri: rtsp://host:port/path
    # GST pipeline variable substitution:
    # - uri: nvr.camera.uri
    # - camera_id: release full name | fullnameOverride
    pipeline: |-
      videotestsrc is-live=true
        ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=1920,height=1080 ! tee name=src
      src.
        ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! queue ! nvvideoconvert
        ! queue ! nvjpegenc quality=75 ! nvdsmqttsink
    # One pipeline can define multiple streams that we define by index to a peripheral
    peripherals:
      - name: Teknoir-NVR
        id: teknoir-nvr
    motion:
      # Number of frames to skip inference when no motion detected
      inactiveInterval: 900
      # Number of frames to skip inference when motion is detected
      activeInterval: 0
    outputTensorMeta: false
  # The path to the models directory
  modelRepositoryPath: /opt/teknoir/models
  # Trackers to be installed via a shared mounted host path (volume)
  trackers: [ ]
  # The path to the tracker directory
  trackerRepositoryPath: /opt/teknoir/trackers
  # The path to the video storage
  videoStoragePath: /opt/teknoir/video/segments
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/nvr
    # Overrides the image tag whose default is "ds7.1-gst1.24.12".
    # ds7.1-gst1.24.12: Nvidia Ada Lovelace GPU on AMD64
    # ds7-gst1.24.7-l4t: Nvidia Orin(tegra) on ARM64
    tag: ds8.0-gst1.26.8
  # Set the log level for the nvr
  # - DEBUG
  # - INFO
  # - WARNING
  # - ERROR
  debugLevel: INFO
  mqtt:
    # Local MQTT broker
    broker: mqtt.kube-system
    port: 1883
    qos: 2
    keepAliveInterval: 10
    connectRetryInterval: 10
    # Topic prefix for generated topic <topicPrefix>/<camera_id: release full name | fullnameOverride>
    topicPrefix: camera/frames
    # Number of frames to queue before dropping
    queueLimit: 15
    # Send metrics collected through MQTT
    metrics: true
    metricsTopic: toe/state
    # Send events without inference calculated
    nonInferenceEvents: true
    # Send events without motion detected
    nonMotionEvents: true
  healthz:
    enabled: true
    bind: :8000
    threshold: 20.0
  livenessProbe:
    initialDelaySeconds: 300 # In case the tracker models take long to load
    periodSeconds: 6
    failureThreshold: 10
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nvdewarper:
    enabled: false
    mountPath: /app/nvdewarper_config
    # Maximum number of streams is 4 per NVR
    nvdewarper_1_enabled: false
    # Mount path for the nvdewarper config file: <mountPath>/nvdewarper_1_config.txt
    nvdewarper_1_config: |
      [property]
      output-width=1920
      output-height=1080
      num-batch-buffers=1
      [surface0]
      surface-index=0
      projection-type=1
      width=1920
      height=1080
      rot-axes=ZXY
      pitch=45
      yaw=0
      roll=0
      src-fov=180
      src-x0=2000
      src-y0=1500
      focal-length=960
      distortion=0;0;0;0
    nvdewarper_2_enabled: false
    # Mount path for the nvdewarper config file: <mountPath>/nvdewarper_2_config.txt
    nvdewarper_2_config: |
      [property]
      output-width=1920
      output-height=1080
      num-batch-buffers=1
      [surface0]
      surface-index=0
      projection-type=1
      width=1920
      height=1080
      rot-axes=ZXY
      pitch=45
      yaw=0
      roll=90
      src-fov=180
      src-x0=2000
      src-y0=1500
      focal-length=960
      distortion=0;0;0;0
    nvdewarper_3_enabled: false
    # Mount path for the nvdewarper config file: <mountPath>/nvdewarper_3_config.txt
    nvdewarper_3_config: |
      [property]
      output-width=1920
      output-height=1080
      num-batch-buffers=1
      [surface0]
      surface-index=0
      projection-type=1
      width=1920
      height=1080
      rot-axes=ZXY
      pitch=45
      yaw=0
      roll=180
      src-fov=180
      src-x0=2000
      src-y0=1500
      focal-length=960
      distortion=0;0;0;0
    nvdewarper_4_enabled: false
    # Mount path for the nvdewarper config file: <mountPath>/nvdewarper_4_config.txt
    nvdewarper_4_config: |
      [property]
      output-width=1920
      output-height=1080
      num-batch-buffers=1
      [surface0]
      surface-index=0
      projection-type=1
      width=1920
      height=1080
      rot-axes=ZXY
      pitch=45
      yaw=0
      roll=270
      src-fov=180
      src-x0=2000
      src-y0=1500
      focal-length=960
      distortion=0;0;0;0